addd docker auth check

diff --git a/.github/workflows/deployment.yml b/.github/workflows/deployment.yml
--- a/.github/workflows/deployment.yml
+++ b/.github/workflows/deployment.yml
@@ -15,6 +15,25 @@ jobs:
       - name: Set up correct docker driver wich support cash
         uses: docker/setup-buildx-action@v3
 
+            - name: Debug secrets check
+        run: |
+          if [ -z "${{ secrets.DOCKER_USERNAME }}" ]; then
+            echo "❌ DOCKER_USERNAME is EMPTY or not found"
+            exit 1
+          else
+            echo "✅ DOCKER_USERNAME is set (length: ${#USERNAME})"
+          fi
+          
+          if [ -z "${{ secrets.DOCKER_PASSWORD }}" ]; then
+            echo "❌ DOCKER_PASSWORD is EMPTY or not found"
+            exit 1
+          else
+            echo "✅ DOCKER_PASSWORD is set (length: ${#PASSWORD})"
+          fi
+        env:
+          USERNAME: ${{ secrets.DOCKER_USERNAME }}
+          PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
+
       - name: Login to Docker Hub
         uses: docker/login-action@v3
         with:
